# Generated by Django 5.2.4 on 2025-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('men', "Men's Wear"), ('women', "Women's Wear"), ('kids', "Kids' Wear"), ('accessories', 'Accessories'), ('footwear', 'Footwear')], max_length=50)),
                ('product_image', models.ImageField(upload_to='img')),
                ('product_title', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_detail', models.CharField(max_length=1000000)),
            ],
        ),
    ]
